### your site title here

title: Kaile Cathy Fang
description: B.A. Psychology | McGill University | motto

baseurl: "/" #name of GitHub repository
url: "https://fancatfkl.github.io" #custom url to be used instead of GitHub repository
email: kaile.fang@mail.mcgill.ca

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
linkedin: "www.linkedin.com/in/kaile-fang-28a7a226b"
github: "https://github.com/fancatfkl"
orcid: "https://orcid.org/0009-0003-0557-4089"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
